PANEL_DATA_DIR=/opt/proxy-panel
PANEL_BIND=0.0.0.0
PANEL_PORT=2333
PANEL_SECURE_COOKIE=0
PANEL_AUTO_INSTALL_RUNTIMES=1
PANEL_UID=10001
PANEL_GID=10001
GOMEMLIMIT=96MiB
GOGC=75
TZ=Asia/Shanghai
LD_LIBRARY_PATH=/opt/proxy-panel/glibc/lib

export PANEL_DATA_DIR PANEL_BIND PANEL_PORT PANEL_SECURE_COOKIE
export PANEL_AUTO_INSTALL_RUNTIMES PANEL_UID PANEL_GID
export GOMEMLIMIT GOGC TZ LD_LIBRARY_PATH
