<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { api, APIError, type Audit, type Backup, type ClientConfig, type Node, type NodeInput, type NodeType, type Traffic, type UpdateComponent, type UpdateStatus } from './api'
import { copyToClipboard } from './clipboard'
import { applyTheme, getStoredTheme, nextTheme, type Theme } from './theme'

type Phase='loading'|'login'|'change'|'app'
type Page='dashboard'|'nodes'|'traffic'|'updates'|'audit'|'settings'
const phase=ref<Phase>('loading'), page=ref<Page>('dashboard'), busy=ref(false), error=ref(''), notice=ref('')
const theme=ref<Theme>(getStoredTheme())
const password=ref(''), newPassword=ref(''), confirmPassword=ref('')
const nodes=ref<Node[]>([]), traffic=ref<Traffic[]>([]), backups=ref<Backup[]>([]), audits=ref<Audit[]>([])
const update=ref<UpdateStatus|null>(null), selectedType=ref<NodeType>('snell'), showEditor=ref(false), editing=ref<Node|null>(null), showDetails=ref(false), detailTitle=ref(''), detailText=ref(''), detailConfig=ref<ClientConfig|null>(null), detailNode=ref<Node|null>(null)
const copiedKey=ref(''), showTrafficEditor=ref(false), trafficEditing=ref<Traffic|null>(null), trafficQuotaGiB=ref(0), trafficResetDay=ref(1)
const form=ref<NodeInput>(blank('snell'))
const nav:Array<{id:Page;label:string;icon:string}>=[{id:'dashboard',label:'仪表盘',icon:'⌁'},{id:'nodes',label:'节点管理',icon:'◆'},{id:'traffic',label:'流量管理',icon:'↕'},{id:'updates',label:'更新与备份',icon:'↻'},{id:'audit',label:'日志与审计',icon:'≡'},{id:'settings',label:'系统设置',icon:'⚙'}]
const filteredNodes=computed(()=>nodes.value.filter(node=>node.type===selectedType.value))
const counts=computed(()=>({snell:nodes.value.filter(n=>n.type==='snell').length,ss2022:nodes.value.filter(n=>n.type==='ss2022').length,shadowtls:nodes.value.filter(n=>n.type==='shadowtls').length}))
const publicTraffic=computed(()=>traffic.value.filter(item=>{const node=nodes.value.find(value=>value.id===item.nodeId);return node&& !['127.0.0.1','::1','localhost'].includes(node.listenHost)}))
const trafficTotals=computed(()=>publicTraffic.value.reduce((sum,item)=>({upload:sum.upload+item.uploadBytes,download:sum.download+item.downloadBytes}),{upload:0,download:0}))

function blank(type:NodeType):NodeInput { if(type==='snell')return{type,name:'新 Snell 节点',runtimeVersion:'v5.0.1',listenHost:'127.0.0.1',listenPort:6160,config:{version:'v5',tfo:true}};if(type==='ss2022')return{type,name:'新 SS-2022 节点',runtimeVersion:'v1.24.0',listenHost:'0.0.0.0',listenPort:20000,config:{mode:'tcp_and_udp',method:'2022-blake3-aes-128-gcm',tfo:true}};return{type,name:'新 ShadowTLS 节点',runtimeVersion:'v0.2.25',listenHost:'0.0.0.0',listenPort:8443,backendNodeId:nodes.value.find(n=>n.type!=='shadowtls')?.id,config:{version:'v3',sni:'www.microsoft.com',wildcardSni:'off',tfo:true}} }
function statusLabel(value:string){return({running:'运行中',stopped:'已停止',failed:'失败',degraded:'降级',starting:'启动中',stopping:'停止中',updating:'更新中'} as Record<string,string>)[value]??value}
function typeLabel(value:NodeType){return value==='snell'?'Snell':value==='ss2022'?'SS-2022':'ShadowTLS'}
function bytes(value:number){if(!value)return '0 B';const units=['B','KiB','MiB','GiB','TiB'];const i=Math.min(Math.floor(Math.log(value)/Math.log(1024)),4);return `${(value/1024**i).toFixed(i?1:0)} ${units[i]}`}
function flash(message:string,isError=false){(isError?error:notice).value=message;setTimeout(()=>{error.value='';notice.value=''},4500)}
function toggleTheme(){theme.value=nextTheme(theme.value);applyTheme(theme.value)}
async function initial(){try{const state=await api<{mustChangePassword:boolean}>('/auth/session');phase.value=state.mustChangePassword?'change':'app';if(phase.value==='app')await refresh()}catch{phase.value='login'}}
async function login(){busy.value=true;error.value='';try{const result=await api<{mustChangePassword:boolean}>('/auth/login',{method:'POST',body:JSON.stringify({password:password.value})});password.value='';phase.value=result.mustChangePassword?'change':'app';if(phase.value==='app')await refresh()}catch(e){flash(message(e),true)}finally{busy.value=false}}
async function change(){if(newPassword.value!==confirmPassword.value){flash('两次输入的密码不一致',true);return}busy.value=true;try{await api('/auth/change-password',{method:'POST',body:JSON.stringify({newPassword:newPassword.value})});newPassword.value='';confirmPassword.value='';phase.value='login';flash('密码已修改，全部旧会话已注销，请重新登录')}catch(e){flash(message(e),true)}finally{busy.value=false}}
async function logout(){try{await api('/auth/logout',{method:'POST'})}finally{phase.value='login';nodes.value=[]}}
async function refresh(){const [dash,t,b,a]=await Promise.all([api<any>('/dashboard'),api<Traffic[]>('/traffic'),api<Backup[]>('/backups'),api<Audit[]>('/audit')]);nodes.value=dash.nodes??[];traffic.value=t??[];backups.value=b??[];audits.value=a??[];try{update.value=await api<UpdateStatus>('/updates/status')}catch{update.value=null}}
function openCreate(type:NodeType){editing.value=null;form.value=blank(type);showEditor.value=true}
function openEdit(node:Node){editing.value=node;form.value={name:node.name,runtimeVersion:node.runtimeVersion,listenHost:node.listenHost,listenPort:node.listenPort,backendNodeId:node.backendNodeId,config:{...node.config}};showEditor.value=true}
async function saveNode(){busy.value=true;try{if(editing.value){await api(`/nodes/${editing.value.id}`,{method:'PUT',body:JSON.stringify(form.value)})}else{await api('/nodes',{method:'POST',body:JSON.stringify(form.value)})};showEditor.value=false;await refresh();flash(editing.value?'节点已更新':'节点已创建；缺少运行时时会显示为失败，不会下载未知程序')}catch(e){flash(message(e),true)}finally{busy.value=false}}
async function action(node:Node,act:'start'|'stop'|'restart'){busy.value=true;try{await api(`/nodes/${node.id}/${act}`,{method:'POST'});await refresh();flash(`${node.name}：${act==='start'?'已启动':act==='stop'?'已停止':'已重启'}`)}catch(e){flash(message(e),true)}finally{busy.value=false}}
async function removeNode(node:Node){if(!confirm(`确定删除“${node.name}”？依赖关系会先校验。`))return;try{await api(`/nodes/${node.id}`,{method:'DELETE'});await refresh();flash('节点已删除')}catch(e){flash(message(e),true)}}
async function logs(node:Node){try{const value=await api<{lines:string[]}>(`/nodes/${node.id}/logs`);detailTitle.value=`${node.name} · 日志`;detailText.value=(value.lines??[]).join('\n')||'暂无日志';detailConfig.value=null;detailNode.value=node;showDetails.value=true}catch(e){flash(message(e),true)}}
async function configs(node:Node){try{const value=await api<ClientConfig>(`/nodes/${node.id}/client-configs`);detailTitle.value=`${node.name} · 客户端配置`;detailText.value='';detailConfig.value=value;detailNode.value=node;copiedKey.value='';showDetails.value=true}catch(e){flash(message(e),true)}}
async function copyText(value:string|undefined,key:string){if(!value)return;const copied=await copyToClipboard(value);if(copied){copiedKey.value=key;setTimeout(()=>{if(copiedKey.value===key)copiedKey.value=''},1800)}else flash('自动复制失败，请长按配置文本手动复制',true)}
function openTraffic(item:Traffic){trafficEditing.value=item;trafficQuotaGiB.value=Number((item.quotaBytes/1024**3).toFixed(2));trafficResetDay.value=item.resetDay;showTrafficEditor.value=true}
async function saveTraffic(){if(!trafficEditing.value)return;busy.value=true;try{await api(`/traffic/${trafficEditing.value.nodeId}/quota`,{method:'PUT',body:JSON.stringify({quotaBytes:Math.round(Math.max(0,trafficQuotaGiB.value)*1024**3),resetDay:trafficResetDay.value})});showTrafficEditor.value=false;await refresh();flash('流量限额与重置周期已更新')}catch(e){flash(message(e),true)}finally{busy.value=false}}
async function toggleTraffic(item:Traffic){busy.value=true;try{await api(`/traffic/${item.nodeId}/${item.paused?'resume':'pause'}`,{method:'POST'});await refresh();flash(item.paused?'节点流量已恢复':'节点流量已暂停')}catch(e){flash(message(e),true)}finally{busy.value=false}}
async function resetTraffic(item:Traffic){if(!confirm('清零该节点当前周期的上传和下载流量？'))return;busy.value=true;try{await api(`/traffic/${item.nodeId}/reset`,{method:'POST'});await refresh();flash('节点流量已清零')}catch(e){flash(message(e),true)}finally{busy.value=false}}
async function checkUpdates(){busy.value=true;try{update.value=await api<UpdateStatus>('/updates/check',{method:'POST'});audits.value=await api<Audit[]>('/audit');flash('上游版本对比完成')}catch(e){flash(message(e),true)}finally{busy.value=false}}
async function applyUpdate(item:UpdateComponent){if(!confirm(`更新 ${item.name} 到 ${item.latestVersion}？系统会先自动创建备份，再更新并重启相关节点。`))return;busy.value=true;try{const result=await api<{status:UpdateStatus}>(`/updates/apply`,{method:'POST',body:JSON.stringify({component:item.key,version:item.latestVersion})});update.value=result.status;await refresh();flash(`${item.name} 已更新到 ${item.latestVersion}`)}catch(e){flash(message(e),true)}finally{busy.value=false}}
async function createBackup(){busy.value=true;try{await api('/backups',{method:'POST'});await refresh();flash('一致性备份已创建')}catch(e){flash(message(e),true)}finally{busy.value=false}}
async function deleteBackup(item:Backup){if(!confirm(`删除备份 ${item.filename}？`))return;await api(`/backups/${item.id}`,{method:'DELETE'});await refresh()}
async function restoreBackup(item:Backup){if(!confirm(`恢复 ${item.filename}？当前状态会先自动备份，协议进程会短暂停止，全部会话将注销。`))return;busy.value=true;try{await api(`/backups/${item.id}/restore`,{method:'POST'});phase.value='login';flash('恢复完成，请使用恢复后的密码重新登录')}catch(e){flash(message(e),true)}finally{busy.value=false}}
async function setPage(value:Page){page.value=value;if(value!=='settings')await refresh().catch(e=>flash(message(e),true))}
function message(e:unknown){if(e instanceof APIError){if(e.code==='PASSWORD_CHANGE_REQUIRED')phase.value='change';if(e.status===401)phase.value='login';return e.message}return e instanceof Error?e.message:'请求失败'}
onMounted(initial)
</script>

<template>
  <main v-if="phase==='loading'" class="center"><div class="spinner"></div><p>正在启动安全控制台…</p></main>
  <main v-else-if="phase==='login'" class="auth-shell">
    <button type="button" class="theme-toggle auth-theme-toggle" :aria-label="theme==='dark'?'切换到白天模式':'切换到黑夜模式'" @click="toggleTheme">{{theme==='dark'?'☀ 白天模式':'☾ 黑夜模式'}}</button>
    <section class="auth-card"><div class="brand-mark">P</div><p class="eyebrow">PROXY PANEL</p><h1>欢迎回来</h1><p class="muted">输入管理员密码以继续</p><form @submit.prevent="login"><label>管理员密码<input v-model="password" type="password" autocomplete="current-password" autofocus required></label><button class="primary wide" :disabled="busy">{{busy?'验证中…':'登录控制台'}} </button></form><p class="security-note">面板可通过服务器 IP 访问。首次登录后请立即修改默认密码，并仅向可信 IP 放行管理端口。</p></section>
  </main>
  <main v-else-if="phase==='change'" class="auth-shell">
    <button type="button" class="theme-toggle auth-theme-toggle" :aria-label="theme==='dark'?'切换到白天模式':'切换到黑夜模式'" @click="toggleTheme">{{theme==='dark'?'☀ 白天模式':'☾ 黑夜模式'}}</button>
    <section class="auth-card"><div class="brand-mark warning">!</div><p class="eyebrow">首次登录保护</p><h1>请先修改默认密码</h1><p class="muted">完成前，节点、日志和系统接口均不可访问。</p><form @submit.prevent="change"><label>新密码<input v-model="newPassword" type="password" autocomplete="new-password" required></label><label>确认新密码<input v-model="confirmPassword" type="password" autocomplete="new-password" required></label><p class="hint">4–128 个 Unicode 字符；不能继续使用 password。空格会作为密码内容保留。</p><button class="primary wide" :disabled="busy">修改并注销全部会话</button></form></section>
  </main>
  <div v-else class="app-shell">
    <aside><div class="logo"><span>P</span><div>Proxy Panel</div></div><nav><button v-for="item in nav" :key="item.id" :class="{active:page===item.id}" @click="setPage(item.id)"><i>{{item.icon}}</i>{{item.label}}</button></nav><div class="aside-footer"><button @click="logout">退出登录</button></div></aside>
    <section class="workspace"><header><div><p class="eyebrow">{{nav.find(n=>n.id===page)?.label}}</p><h2>{{page==='dashboard'?'运行概览':nav.find(n=>n.id===page)?.label}}</h2></div><div class="header-actions"><span class="clock">{{new Date().toLocaleDateString('zh-CN')}}</span><button type="button" class="ghost theme-toggle" :aria-label="theme==='dark'?'切换到白天模式':'切换到黑夜模式'" @click="toggleTheme">{{theme==='dark'?'☀ 白天模式':'☾ 黑夜模式'}}</button><button class="ghost" @click="refresh">刷新</button></div></header>
      <div v-if="notice" class="toast success">{{notice}}</div><div v-if="error" class="toast error">{{error}}</div>
      <div v-if="page==='dashboard'" class="content">
        <div class="stats dashboard-stats"><article><span>Snell</span><b>{{counts.snell}}</b><small>多版本实例</small></article><article><span>SS-2022</span><b>{{counts.ss2022}}</b><small>TCP / UDP</small></article><article><span>ShadowTLS</span><b>{{counts.shadowtls}}</b><small>v3 前端</small></article><article><span>节点总流量</span><b>{{bytes(trafficTotals.upload+trafficTotals.download)}}</b><small>上传 {{bytes(trafficTotals.upload)}} · 下载 {{bytes(trafficTotals.download)}}</small></article></div>
        <section class="panel"><div class="panel-title"><div><h3>节点健康</h3><p>期望状态与实际进程状态</p></div><button class="primary" @click="page='nodes'">管理节点</button></div><div class="node-grid"><article v-for="node in nodes" :key="node.id" class="node-card"><div><span :class="['status-dot',node.actualState]"></span><small>{{typeLabel(node.type)}}</small></div><h4>{{node.name}}</h4><p>{{node.listenHost}}:{{node.listenPort}}</p><footer><span :class="['badge',node.actualState]">{{statusLabel(node.actualState)}}</span><span>r{{node.revision}}</span></footer></article></div></section>
      </div>
      <div v-else-if="page==='nodes'" class="content"><div class="tabs"><button v-for="type in (['snell','ss2022','shadowtls'] as NodeType[])" :key="type" :class="{active:selectedType===type}" @click="selectedType=type">{{typeLabel(type)}} <span>{{counts[type]}}</span></button><button class="primary push" @click="openCreate(selectedType)">＋ 新建节点</button></div><section class="panel table-panel"><table><thead><tr><th>节点</th><th>监听</th><th>版本 / 模式</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="node in filteredNodes" :key="node.id"><td><b>{{node.name}}</b><small>{{node.id}}</small></td><td><code>{{node.listenHost}}:{{node.listenPort}}</code></td><td>{{node.config.version||node.config.method||node.runtimeVersion}}</td><td><span :class="['badge',node.actualState]">{{statusLabel(node.actualState)}}</span><small v-if="node.lastError" class="danger">{{node.lastError}}</small></td><td class="actions"><button @click="openEdit(node)">编辑</button><button @click="action(node,node.desiredState==='running'?'stop':'start')">{{node.desiredState==='running'?'停止':'启动'}}</button><button @click="action(node,'restart')">重启</button><button @click="configs(node)">配置</button><button @click="logs(node)">日志</button><button class="danger-text" @click="removeNode(node)">删除</button></td></tr></tbody></table><div v-if="!filteredNodes.length" class="empty">暂无节点</div></section></div>
      <div v-else-if="page==='traffic'" class="content"><div class="callout"><b>统计边界</b><span>只统计公网端口的实际入站与出站字节；排除本机 ShadowTLS 转发，避免重复计量。</span></div><section class="panel table-panel"><table><thead><tr><th>节点</th><th>周期</th><th>上传</th><th>下载</th><th>限额</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="item in publicTraffic" :key="item.nodeId"><td><b>{{nodes.find(n=>n.id===item.nodeId)?.name||item.nodeId}}</b></td><td>{{item.period}} · 每月 {{item.resetDay}} 日重置</td><td>{{bytes(item.uploadBytes)}}</td><td>{{bytes(item.downloadBytes)}}</td><td>{{item.quotaBytes?bytes(item.quotaBytes):'不限'}}</td><td><span :class="['badge',item.paused?'failed':'running']">{{item.paused?(item.pausedByQuota?'超限暂停':'已暂停'):'正常'}}</span></td><td class="actions"><button @click="openTraffic(item)">设置</button><button @click="toggleTraffic(item)">{{item.paused?'恢复':'暂停'}}</button><button @click="resetTraffic(item)">清零</button></td></tr></tbody></table><div v-if="!publicTraffic.length" class="empty">暂无公网节点</div></section></div>
      <div v-else-if="page==='updates'" class="content"><section class="panel update-center"><div class="panel-title"><div><h3>上游版本对比与一键更新</h3><p>对照原 GitHub 脚本模块和官方运行时版本，更新前自动备份</p></div><button class="primary" :disabled="busy" @click="checkUpdates">{{busy?'检查中…':'检查上游版本'}}</button></div><div class="update-summary"><span>面板 {{update?.panelVersion||'dev'}}</span><span>适配器 Schema {{update?.adapter?.schemaVersion||'—'}}</span><span>最近检查 {{update?.checkedAt?new Date(update.checkedAt).toLocaleString('zh-CN'):'尚未检查'}}</span></div><p class="callout">{{update?.message||'更新元数据尚未初始化。'}}</p><div class="component-list"><article v-for="item in update?.components||[]" :key="item.key" class="component-card"><div class="component-main"><small>{{item.category==='runtime'?'运行时':'原脚本对照'}}</small><h4>{{item.name}}</h4><a :href="item.sourceUrl" target="_blank" rel="noreferrer">查看上游来源</a></div><div class="version-compare"><span>当前<b>{{item.currentVersion}}</b></span><i>→</i><span>上游<b>{{item.latestVersion}}</b></span></div><div class="component-state"><span :class="['badge',item.updateAvailable?(item.canApply?'degraded':'failed'):'running']">{{item.updateAvailable?(item.canApply?'可更新':'待适配'):'已是最新'}}</span><small>{{item.message}}</small><button v-if="item.canApply" class="primary" :disabled="busy" @click="applyUpdate(item)">备份并更新</button></div></article></div></section><section class="panel backup-panel"><div class="panel-title"><div><h3>配置备份</h3><p>SQLite 一致性快照、配置与主密钥；一键更新也会自动创建</p></div><button class="primary" :disabled="busy" @click="createBackup">创建备份</button></div><div class="backup" v-for="item in backups" :key="item.id"><div><b>{{item.filename}}</b><small>{{bytes(item.size)}} · {{new Date(item.createdAt).toLocaleString('zh-CN')}}</small></div><div class="actions"><button @click="restoreBackup(item)">恢复</button><button class="danger-text" @click="deleteBackup(item)">删除</button></div></div><div v-if="!backups.length" class="empty">还没有备份</div></section></div>
      <div v-else-if="page==='audit'" class="content"><section class="panel table-panel"><table><thead><tr><th>时间</th><th>具体操作</th><th>目标</th><th>来源</th><th>结果</th></tr></thead><tbody><tr v-for="item in audits" :key="item.id"><td>{{new Date(item.createdAt).toLocaleString('zh-CN')}}</td><td><b>{{item.description}}</b><small>{{item.detailDescription||item.action}}</small></td><td>{{item.targetDescription}}<small>{{item.targetId||'—'}}</small></td><td>{{item.remoteIp}}</td><td><span :class="['badge',item.success?'running':'failed']">{{item.success?'成功':'失败'}}</span></td></tr></tbody></table></section></div>
      <div v-else class="content two-col"><section class="panel"><h3>安全设置</h3><p class="muted">修改密码会立即注销包括当前会话在内的全部 Session。</p><button class="primary" @click="phase='change'">修改管理员密码</button></section><section class="panel"><h3>公网访问提醒</h3><p class="callout warning-box">面板默认监听 0.0.0.0:8080，可直接通过服务器 IP 访问。请立即修改默认密码、仅向可信 IP 放行管理端口；长期使用建议配置 HTTPS，届时启用 PANEL_SECURE_COOKIE=1。</p></section></div>
    </section>
  </div>
  <div v-if="showEditor" class="modal" @click.self="showEditor=false"><form class="dialog" @submit.prevent="saveNode"><div class="panel-title"><div><p class="eyebrow">{{editing?'编辑':'创建'}} {{typeLabel((editing?.type||form.type) as NodeType)}}</p><h3>{{form.name}}</h3></div><button type="button" class="close" @click="showEditor=false">×</button></div><div class="form-grid"><label>名称<input v-model="form.name" required></label><label>监听地址<input v-model="form.listenHost" required></label><label>监听端口<input v-model.number="form.listenPort" type="number" min="1" max="65535" required></label><template v-if="(editing?.type||form.type)==='snell'"><label>协议版本<select v-model="form.config.version"><option>v4</option><option>v5</option><option>v6</option></select></label></template><template v-if="(editing?.type||form.type)==='ss2022'"><label>加密方法<select v-model="form.config.method"><option>2022-blake3-aes-128-gcm</option><option>2022-blake3-aes-256-gcm</option><option>2022-blake3-chacha20-poly1305</option></select></label><label>模式<select v-model="form.config.mode"><option value="tcp_and_udp">TCP + UDP</option><option value="tcp_only">仅 TCP</option><option value="udp_only">仅 UDP</option></select></label></template><template v-if="(editing?.type||form.type)==='shadowtls'"><label>后端节点<select v-model="form.backendNodeId"><option v-for="node in nodes.filter(n=>n.type!=='shadowtls')" :key="node.id" :value="node.id">{{node.name}}</option></select></label><label>SNI<input v-model="form.config.sni" required></label><label>wildcard-sni<select v-model="form.config.wildcardSni"><option value="off">关闭</option><option value="authed">已认证</option><option value="all">全部（高风险）</option></select></label></template><label class="check"><input v-model="form.config.tfo" type="checkbox">启用 TCP Fast Open</label><label>密钥 / 密码（留空自动生成或保持原值）<input v-model="form.secret" type="password" autocomplete="new-password"></label></div><footer class="dialog-actions"><button type="button" @click="showEditor=false">取消</button><button class="primary" :disabled="busy">{{busy?'应用中…':'验证并应用'}}</button></footer></form></div>
  <div v-if="showTrafficEditor" class="modal" @click.self="showTrafficEditor=false"><form class="dialog traffic-dialog" @submit.prevent="saveTraffic"><div class="panel-title"><div><p class="eyebrow">流量管理</p><h3>{{nodes.find(n=>n.id===trafficEditing?.nodeId)?.name}}</h3></div><button type="button" class="close" @click="showTrafficEditor=false">×</button></div><div class="form-grid"><label>月流量限额（GiB，0 = 不限）<input v-model.number="trafficQuotaGiB" type="number" min="0" step="0.1" required></label><label>每月重置日<input v-model.number="trafficResetDay" type="number" min="1" max="28" required></label></div><p class="hint">流量达到限额后会自动暂停公网端口，到下一计费周期自动恢复。</p><footer class="dialog-actions"><button type="button" @click="showTrafficEditor=false">取消</button><button class="primary" :disabled="busy">保存设置</button></footer></form></div>
  <div v-if="showDetails" class="modal" @click.self="showDetails=false"><section class="dialog details"><div class="panel-title"><div><h3>{{detailTitle}}</h3><p v-if="detailConfig">{{detailConfig.protocolLabel}}</p></div><button class="close" @click="showDetails=false">×</button></div><template v-if="detailConfig"><div v-if="detailNode?.type==='shadowtls'" class="callout config-explain"><b>这是组合配置，不是协议错配</b><span>客户端先连接 ShadowTLS 公网端口，再由服务器转发到 {{detailConfig.protocolLabel.includes('Snell')?'Snell':'SS-2022'}} 后端；因此配置中会同时出现两种协议参数。</span></div><div :class="['config-layout',{'no-qr':!detailConfig.qrCode}]"><div class="config-sections"><section v-if="detailConfig.primary" class="config-block"><div><b>{{detailConfig.primaryLabel}}</b><button :class="{copied:copiedKey==='primary'}" @click="copyText(detailConfig.primary,'primary')">{{copiedKey==='primary'?'✓':'复制'}}</button></div><pre>{{detailConfig.primary}}</pre></section><p v-if="detailConfig.importNote" class="callout import-note">{{detailConfig.importNote}}</p><section v-if="detailConfig.surge" class="config-block"><div><b>{{detailConfig.surgeLabel||'Surge [Proxy] 节点行'}}</b><button v-if="!detailConfig.surge.startsWith('#')" :class="{copied:copiedKey==='surge'}" @click="copyText(detailConfig.surge,'surge')">{{copiedKey==='surge'?'✓':'复制'}}</button></div><pre>{{detailConfig.surge}}</pre></section><section v-if="detailConfig.surgeAlternative" class="config-block"><div><b>{{detailConfig.surgeAlternativeLabel}}</b><button :class="{copied:copiedKey==='surge-alt'}" @click="copyText(detailConfig.surgeAlternative,'surge-alt')">{{copiedKey==='surge-alt'?'✓':'复制'}}</button></div><pre>{{detailConfig.surgeAlternative}}</pre></section><p v-if="detailConfig.surgeNote" class="config-note">{{detailConfig.surgeNote}}</p><section class="config-block"><div><b>Clash / Mihomo 配置</b><button v-if="!detailConfig.clash.startsWith('#')" :class="{copied:copiedKey==='clash'}" @click="copyText(detailConfig.clash,'clash')">{{copiedKey==='clash'?'✓':'复制'}}</button></div><pre>{{detailConfig.clash}}</pre></section><section v-if="detailConfig.clashInline" class="config-block"><div><b>Clash / Mihomo 单行配置</b><button :class="{copied:copiedKey==='clash-inline'}" @click="copyText(detailConfig.clashInline,'clash-inline')">{{copiedKey==='clash-inline'?'✓':'复制'}}</button></div><pre>{{detailConfig.clashInline}}</pre></section><p v-if="detailConfig.warning" class="callout warning-box">{{detailConfig.warning}}</p></div><aside v-if="detailConfig.qrCode" class="qr-card"><img :src="detailConfig.qrCode" alt="Shadowrocket 可导入的 SS 配置二维码"><b>Shadowrocket 扫码导入</b><small>{{detailConfig.qrCodeLabel}}</small></aside></div><p class="secret-note">配置包含完整密钥，仅在已登录的安全会话内展示。请勿截图或转发给无关人员。</p></template><pre v-else>{{detailText}}</pre></section></div>
</template>
